#!/bin/bash

export COLOR_WINDOW_BORDER="#1A1B26"
export COLOR_WINDOW_BORDER_PRIMARY="#D8DEE8"

export BAR_BACKGROUND="#1A1B26"
export BAR_FOREGROUND="#A9B1D6"
export BAR_POWER_DEPLETED="#414868"
export WORKSPACE_ACTIVE_FOREGROUND="#7AA2F7"
export WORKSPACE_URGENT_FOREGROUND="#F7768E"
export WORKSPACE_OTHER_FOREGROUND="#A9B1D6"

