#!/bin/bash

# Source colors
source ~/.config/scripts/colors.sh
source ~/.config/scripts/scaling.sh

bspc monitor -d I II III IV V VI

bspc config automatic_scheme longest_side

bspc config border_width $WINDOW_BORDER_WIDTH
bspc config window_gap $WINDOW_GAP
bspc config normal_border_color $COLOR_WINDOW_BORDER
bspc config focused_border_color $COLOR_WINDOW_BORDER_PRIMARY

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Launch keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Set background
feh --bg-scale ~/.config/wallpaper/wallpaper.png

# Launch topbar
polybar top_bar --config=~/.config/polybar/config.ini
